renderscript example builds but it doesnt run, or perhaps i print
the wrong thing

2019-08-01 01:12:08.826 15506-15506/? I/art: Late-enabling -Xcheck:jni
2019-08-01 01:12:08.935 15506-15506/com.example.quizactivity W/art: Before Android 4.1, method android.graphics.PorterDuffColorFilter androidx.vectordrawable.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
2019-08-01 01:12:08.941 15506-15506/com.example.quizactivity D/martin: onCreate
2019-08-01 01:12:08.970 15506-15506/com.example.quizactivity I/art: Rejecting re-init on previously-failed class java.lang.Class<androidx.core.view.ViewCompat$OnUnhandledKeyEventListenerWrapper>: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/view/View$OnUnhandledKeyEventListener;
2019-08-01 01:12:08.970 15506-15506/com.example.quizactivity I/art:     at void androidx.core.view.ViewCompat.setBackground(android.view.View, android.graphics.drawable.Drawable) (ViewCompat.java:2341)
2019-08-01 01:12:08.970 15506-15506/com.example.quizactivity I/art:     at void androidx.appcompat.widget.ActionBarContainer.<init>(android.content.Context, android.util.AttributeSet) (ActionBarContainer.java:62)
2019-08-01 01:12:08.970 15506-15506/com.example.quizactivity I/art:     at java.lang.Object java.lang.reflect.Constructor.newInstance0!(java.lang.Object[]) (Constructor.java:-2)
2019-08-01 01:12:08.970 15506-15506/com.example.quizactivity I/art:     at java.lang.Object java.lang.reflect.Constructor.newInstance(java.lang.Object[]) (Constructor.java:430)
2019-08-01 01:12:08.970 15506-15506/com.example.quizactivity I/art:     at android.view.View android.view.LayoutInflater.createView(java.lang.String, java.lang.String, android.util.AttributeSet) (LayoutInflater.java:645)
2019-08-01 01:12:08.970 15506-15506/com.example.quizactivity I/art:     at android.view.View android.view.LayoutInflater.createViewFromTag(android.view.View, java.lang.String, android.content.Context, android.util.AttributeSet, boolean) (LayoutInflater.java:787)
2019-08-01 01:12:08.971 15506-15506/com.example.quizactivity I/art:     at android.view.View android.view.LayoutInflater.createViewFromTag(android.view.View, java.lang.String, android.content.Context, android.util.AttributeSet) (LayoutInflater.java:727)
2019-08-01 01:12:08.971 15506-15506/com.example.quizactivity I/art:     at void android.view.LayoutInflater.rInflate(org.xmlpull.v1.XmlPullParser, android.view.View, android.content.Context, android.util.AttributeSet, boolean) (LayoutInflater.java:858)
2019-08-01 01:12:08.971 15506-15506/com.example.quizactivity I/art:     at void android.view.LayoutInflater.rInflateChildren(org.xmlpull.v1.XmlPullParser, android.view.View, android.util.AttributeSet, boolean) (LayoutInflater.java:821)
2019-08-01 01:12:08.971 15506-15506/com.example.quizactivity I/art:     at android.view.View android.view.LayoutInflater.inflate(org.xmlpull.v1.XmlPullParser, android.view.ViewGroup, boolean) (LayoutInflater.java:518)
2019-08-01 01:12:08.971 15506-15506/com.example.quizactivity I/art:     at android.view.View android.view.LayoutInflater.inflate(int, android.view.ViewGroup, boolean) (LayoutInflater.java:426)
2019-08-01 01:12:08.971 15506-15506/com.example.quizactivity I/art:     at android.view.View android.view.LayoutInflater.inflate(int, android.view.ViewGroup) (LayoutInflater.java:377)
2019-08-01 01:12:08.971 15506-15506/com.example.quizactivity I/art:     at android.view.ViewGroup androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor() (AppCompatDelegateImpl.java:607)
2019-08-01 01:12:08.971 15506-15506/com.example.quizactivity I/art:     at void androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor() (AppCompatDelegateImpl.java:518)
2019-08-01 01:12:08.971 15506-15506/com.example.quizactivity I/art:     at void androidx.appcompat.app.AppCompatDelegateImpl.setContentView(int) (AppCompatDelegateImpl.java:466)
2019-08-01 01:12:08.971 15506-15506/com.example.quizactivity I/art:     at void androidx.appcompat.app.AppCompatActivity.setContentView(int) (AppCompatActivity.java:140)
2019-08-01 01:12:08.971 15506-15506/com.example.quizactivity I/art:     at void com.example.quizactivity.MainActivity.onCreate(android.os.Bundle) (MainActivity.kt:11)
2019-08-01 01:12:08.971 15506-15506/com.example.quizactivity I/art:     at void android.app.Activity.performCreate(android.os.Bundle) (Activity.java:6684)
2019-08-01 01:12:08.971 15506-15506/com.example.quizactivity I/art:     at void android.app.Instrumentation.callActivityOnCreate(android.app.Activity, android.os.Bundle) (Instrumentation.java:1119)
2019-08-01 01:12:08.971 15506-15506/com.example.quizactivity I/art:     at android.app.Activity android.app.ActivityThread.performLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent) (ActivityThread.java:2637)
2019-08-01 01:12:08.971 15506-15506/com.example.quizactivity I/art:     at void android.app.ActivityThread.handleLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:2751)
2019-08-01 01:12:08.971 15506-15506/com.example.quizactivity I/art:     at void android.app.ActivityThread.-wrap12(android.app.ActivityThread, android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:-1)
2019-08-01 01:12:08.971 15506-15506/com.example.quizactivity I/art:     at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1496)
2019-08-01 01:12:08.971 15506-15506/com.example.quizactivity I/art:     at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:102)
2019-08-01 01:12:08.971 15506-15506/com.example.quizactivity I/art:     at void android.os.Looper.loop() (Looper.java:154)
2019-08-01 01:12:08.971 15506-15506/com.example.quizactivity I/art:     at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6186)
2019-08-01 01:12:08.971 15506-15506/com.example.quizactivity I/art:     at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
2019-08-01 01:12:08.971 15506-15506/com.example.quizactivity I/art:     at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:889)
2019-08-01 01:12:08.971 15506-15506/com.example.quizactivity I/art:     at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:779)
2019-08-01 01:12:08.971 15506-15506/com.example.quizactivity I/art: Caused by: java.lang.ClassNotFoundException: Didn't find class "android.view.View$OnUnhandledKeyEventListener" on path: DexPathList[[zip file "/data/app/com.example.quizactivity-1/base.apk"],nativeLibraryDirectories=[/data/app/com.example.quizactivity-1/lib/arm64, /data/app/com.example.quizactivity-1/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
2019-08-01 01:12:08.971 15506-15506/com.example.quizactivity I/art:     at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:56)
2019-08-01 01:12:08.971 15506-15506/com.example.quizactivity I/art:     at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:380)
2019-08-01 01:12:08.971 15506-15506/com.example.quizactivity I/art:     at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
2019-08-01 01:12:08.971 15506-15506/com.example.quizactivity I/art:     at void androidx.core.view.ViewCompat.setBackground(android.view.View, android.graphics.drawable.Drawable) (ViewCompat.java:2341)
2019-08-01 01:12:08.971 15506-15506/com.example.quizactivity I/art:     at void androidx.appcompat.widget.ActionBarContainer.<init>(android.content.Context, android.util.AttributeSet) (ActionBarContainer.java:62)
2019-08-01 01:12:08.971 15506-15506/com.example.quizactivity I/art:     at java.lang.Object java.lang.reflect.Constructor.newInstance0!(java.lang.Object[]) (Constructor.java:-2)
2019-08-01 01:12:08.971 15506-15506/com.example.quizactivity I/art:     at java.lang.Object java.lang.reflect.Constructor.newInstance(java.lang.Object[]) (Constructor.java:430)
2019-08-01 01:12:08.971 15506-15506/com.example.quizactivity I/art:     at android.view.View android.view.LayoutInflater.createView(java.lang.String, java.lang.String, android.util.AttributeSet) (LayoutInflater.java:645)
2019-08-01 01:12:08.971 15506-15506/com.example.quizactivity I/art:     at android.view.View android.view.LayoutInflater.createViewFromTag(android.view.View, java.lang.String, android.content.Context, android.util.AttributeSet, boolean) (LayoutInflater.java:787)
2019-08-01 01:12:08.971 15506-15506/com.example.quizactivity I/art:     at android.view.View android.view.LayoutInflater.createViewFromTag(android.view.View, java.lang.String, android.content.Context, android.util.AttributeSet) (LayoutInflater.java:727)
2019-08-01 01:12:08.971 15506-15506/com.example.quizactivity I/art:     at void android.view.LayoutInflater.rInflate(org.xmlpull.v1.XmlPullParser, android.view.View, android.content.Context, android.util.AttributeSet, boolean) (LayoutInflater.java:858)
2019-08-01 01:12:08.972 15506-15506/com.example.quizactivity I/art:     at void android.view.LayoutInflater.rInflateChildren(org.xmlpull.v1.XmlPullParser, android.view.View, android.util.AttributeSet, boolean) (LayoutInflater.java:821)
2019-08-01 01:12:08.972 15506-15506/com.example.quizactivity I/art:     at android.view.View android.view.LayoutInflater.inflate(org.xmlpull.v1.XmlPullParser, android.view.ViewGroup, boolean) (LayoutInflater.java:518)
2019-08-01 01:12:08.972 15506-15506/com.example.quizactivity I/art:     at android.view.View android.view.LayoutInflater.inflate(int, android.view.ViewGroup, boolean) (LayoutInflater.java:426)
2019-08-01 01:12:08.972 15506-15506/com.example.quizactivity I/art:     at android.view.View android.view.LayoutInflater.inflate(int, android.view.ViewGroup) (LayoutInflater.java:377)
2019-08-01 01:12:08.972 15506-15506/com.example.quizactivity I/art:     at android.view.ViewGroup androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor() (AppCompatDelegateImpl.java:607)
2019-08-01 01:12:08.972 15506-15506/com.example.quizactivity I/art:     at void androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor() (AppCompatDelegateImpl.java:518)
2019-08-01 01:12:08.972 15506-15506/com.example.quizactivity I/art:     at void androidx.appcompat.app.AppCompatDelegateImpl.setContentView(int) (AppCompatDelegateImpl.java:466)
2019-08-01 01:12:08.972 15506-15506/com.example.quizactivity I/art:     at void androidx.appcompat.app.AppCompatActivity.setContentView(int) (AppCompatActivity.java:140)
2019-08-01 01:12:08.972 15506-15506/com.example.quizactivity I/art:     at void com.example.quizactivity.MainActivity.onCreate(android.os.Bundle) (MainActivity.kt:11)
2019-08-01 01:12:08.972 15506-15506/com.example.quizactivity I/art:     at void android.app.Activity.performCreate(android.os.Bundle) (Activity.java:6684)
2019-08-01 01:12:08.972 15506-15506/com.example.quizactivity I/art:     at void android.app.Instrumentation.callActivityOnCreate(android.app.Activity, android.os.Bundle) (Instrumentation.java:1119)
2019-08-01 01:12:08.972 15506-15506/com.example.quizactivity I/art:     at android.app.Activity android.app.ActivityThread.performLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent) (ActivityThread.java:2637)
2019-08-01 01:12:08.972 15506-15506/com.example.quizactivity I/art:     at void android.app.ActivityThread.handleLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:2751)
2019-08-01 01:12:08.972 15506-15506/com.example.quizactivity I/art:     at void android.app.ActivityThread.-wrap12(android.app.ActivityThread, android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:-1)
2019-08-01 01:12:08.972 15506-15506/com.example.quizactivity I/art:     at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1496)
2019-08-01 01:12:08.972 15506-15506/com.example.quizactivity I/art:     at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:102)
2019-08-01 01:12:08.972 15506-15506/com.example.quizactivity I/art:     at void android.os.Looper.loop() (Looper.java:154)
2019-08-01 01:12:08.972 15506-15506/com.example.quizactivity I/art:     at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6186)
2019-08-01 01:12:08.972 15506-15506/com.example.quizactivity I/art:     at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
2019-08-01 01:12:08.972 15506-15506/com.example.quizactivity I/art:     at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:889)
2019-08-01 01:12:08.972 15506-15506/com.example.quizactivity I/art:     at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:779)
2019-08-01 01:12:09.098 15506-15506/com.example.quizactivity V/RenderScript_jni: RS native mode
2019-08-01 01:12:09.101 15506-15506/com.example.quizactivity V/RenderScript_jni: Unable to load libRSSupportIO.so, USAGE_IO not supported
2019-08-01 01:12:09.109 15506-15506/com.example.quizactivity E/linker: library "/system/lib64/libblasV8.so" ("/system/lib64/libblasV8.so") needed or dlopened by "/system/lib64/libnativeloader.so" is not accessible for the namespace: [name="classloader-namespace", ld_library_paths="", default_library_paths="/data/app/com.example.quizactivity-1/lib/arm64:/data/app/com.example.quizactivity-1/base.apk!/lib/arm64-v8a", permitted_paths="/data:/mnt/expand:/data/data/com.example.quizactivity"]
2019-08-01 01:12:09.110 15506-15506/com.example.quizactivity V/RenderScript_jni: Unable to load BLAS lib, ONLY BNNM will be supported: java.lang.UnsatisfiedLinkError: dlopen failed: library "/system/lib64/libblasV8.so" needed or dlopened by "/system/lib64/libnativeloader.so" is not accessible for the namespace "classloader-namespace"
2019-08-01 01:12:09.216 15506-15522/com.example.quizactivity V/RenderScript: Successfully loaded runtime: libRSDriver_adreno.so
2019-08-01 01:12:09.266 15506-15522/com.example.quizactivity E/RenderScript: Unable to open shared library (/data/user/0/com.example.quizactivity/cache/librs.sum.so): (null)
2019-08-01 01:12:09.269 15506-15522/com.example.quizactivity V/RenderScript: Invoking /system/bin/bcc with args '/system/bin/bcc -unroll-runtime -scalarize-load-store -rs-global-info -rs-global-info-skip-constant -o sum -output_path /data/user/0/com.example.quizactivity/cache -bclib /system/lib64/libclcore.bc -mtriple aarch64-none-linux-gnueabi -O 3 -aarch64-fix-cortex-a53-835769 -load libbccQTI.so -fPIC -embedRSInfo /data/user/0/com.example.quizactivity/cache/sum.bc -build-checksum 45f9e9ac'
2019-08-01 01:12:10.200 15506-15522/com.example.quizactivity V/RenderScript: Invoking /system/bin/ld.mc with args '/system/bin/ld.mc -shared -nostdlib /system/lib64/libcompiler_rt.so -mtriple=aarch64-none-linux-gnueabi --library-path=/system/vendor/lib64 --library-path=/system/lib64 -lRSDriver_adreno -lm -lc /data/user/0/com.example.quizactivity/cache/sum.o -o /data/user/0/com.example.quizactivity/cache/librs.sum.so'
2019-08-01 01:12:10.359 15506-15506/com.example.quizactivity D/martin: output {[I@914a52d[0]}, {[I@914a52d[1]}, {[I@914a52d[2]}, {[I@914a52d[3]}, {[I@914a52d[4]}, {[I@914a52d[5]}, {[I@914a52d[6]}, {[I@914a52d[7]}, {[I@914a52d[8]}
2019-08-01 01:12:10.363 15506-15506/com.example.quizactivity D/martin: onStart
2019-08-01 01:12:10.365 15506-15506/com.example.quizactivity D/martin: onPostCreate
2019-08-01 01:12:10.372 15506-15506/com.example.quizactivity D/martin: onResume
2019-08-01 01:12:10.376 15506-15506/com.example.quizactivity D/martin: onPostResume
2019-08-01 01:12:10.458 15506-15534/com.example.quizactivity I/Adreno: QUALCOMM build                   : 6818200, Idb2b4cb785
    Build Date                       : 11/18/16
    OpenGL ES Shader Compiler Version: XE031.09.00.04
    Local Branch                     : N25
    Remote Branch                    :
    Remote Branch                    :
    Reconstruct Branch               :
2019-08-01 01:12:10.486 15506-15534/com.example.quizactivity I/OpenGLRenderer: Initialized EGL, version 1.4
2019-08-01 01:12:10.488 15506-15534/com.example.quizactivity D/OpenGLRenderer: Swap behavior 1