camera app compiles but crashes
2019-07-30 23:11:01.816 14631-14631/com.example.quizactivity D/AndroidRuntime: Shutting down VM
2019-07-30 23:11:01.818 14631-14631/com.example.quizactivity E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.quizactivity, PID: 14631
    java.lang.IllegalArgumentException: Unable to get camera ID for use case androidx.camera.core.Preview-5a7bd845-83a8-4c6a-91fd-b883848666ef
        at androidx.camera.camera2.impl.Camera2DeviceSurfaceManager.getCameraIdFromConfig(Camera2DeviceSurfaceManager.java:310)
        at androidx.camera.camera2.impl.Camera2DeviceSurfaceManager.requiresCorrectedAspectRatio(Camera2DeviceSurfaceManager.java:268)
        at androidx.camera.core.Preview.updateUseCaseConfig(Preview.java:387)
        at androidx.camera.core.UseCase.<init>(UseCase.java:92)
        at androidx.camera.core.Preview.<init>(Preview.java:99)
        at com.example.quizactivity.MainActivity.startCamera(MainActivity.kt:73)
        at com.example.quizactivity.MainActivity.access$startCamera(MainActivity.kt:16)
        at com.example.quizactivity.MainActivity$onCreate$1.invoke(MainActivity.kt:23)
        at com.example.quizactivity.MainActivity$onCreate$1.run(MainActivity.kt:16)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6186)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
     Caused by: java.lang.IllegalArgumentException: Option does not exist: Option{id=camerax.core.camera.lensFacing, valueClass=class androidx.camera.core.CameraX$LensFacing, token=null}
        at androidx.camera.core.OptionsBundle.retrieveOption(OptionsBundle.java:107)
        at androidx.camera.core.PreviewConfig.retrieveOption(PreviewConfig.java:73)
        at androidx.camera.core.PreviewConfig.getLensFacing(PreviewConfig.java:178)
        at androidx.camera.camera2.impl.Camera2DeviceSurfaceManager.getCameraIdFromConfig(Camera2DeviceSurfaceManager.java:307)
        at androidx.camera.camera2.impl.Camera2DeviceSurfaceManager.requiresCorrectedAspectRatio(Camera2DeviceSurfaceManager.java:268) 
        at androidx.camera.core.Preview.updateUseCaseConfig(Preview.java:387) 
        at androidx.camera.core.UseCase.<init>(UseCase.java:92) 
        at androidx.camera.core.Preview.<init>(Preview.java:99) 
        at com.example.quizactivity.MainActivity.startCamera(MainActivity.kt:73) 
        at com.example.quizactivity.MainActivity.access$startCamera(MainActivity.kt:16) 
        at com.example.quizactivity.MainActivity$onCreate$1.invoke(MainActivity.kt:23) 
        at com.example.quizactivity.MainActivity$onCreate$1.run(MainActivity.kt:16) 
        at android.os.Handler.handleCallback(Handler.java:751) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6186) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779) 