deploy is failing
019-07-28 20:47:40.714 5926-5926/? I/studio.deploy: DeltaInstall found API level:25
2019-07-28 20:47:40.714 5926-5926/? I/studio.deploy: -t
2019-07-28 20:47:40.714 5926-5926/? I/studio.deploy: -r
2019-07-28 20:47:40.801 5926-5926/? I/studio.deploy: DeltaInstall created session: '1309473271'
2019-07-28 20:47:40.804 5926-5926/? I/studio.deploy: package
2019-07-28 20:47:40.804 5926-5926/? I/studio.deploy: install-write
2019-07-28 20:47:40.805 5926-5926/? I/studio.deploy: -S
2019-07-28 20:47:40.805 5926-5926/? I/studio.deploy: 2162493
2019-07-28 20:47:40.805 5926-5926/? I/studio.deploy: 1309473271
2019-07-28 20:47:40.805 5926-5926/? I/studio.deploy: base.apk
2019-07-28 20:47:40.899 1022-2774/system_process W/FastPrintWriter: Write failure
    java.io.IOException: write failed: EPIPE (Broken pipe)
        at libcore.io.IoBridge.write(IoBridge.java:501)
        at java.io.FileOutputStream.write(FileOutputStream.java:316)
        at com.android.internal.util.FastPrintWriter.flushBytesLocked(FastPrintWriter.java:336)
        at com.android.internal.util.FastPrintWriter.flushLocked(FastPrintWriter.java:359)
        at com.android.internal.util.FastPrintWriter.flush(FastPrintWriter.java:394)
        at android.os.ShellCommand.exec(ShellCommand.java:113)
        at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:18629)
        at android.os.Binder.shellCommand(Binder.java:468)
        at android.os.Binder.onTransact(Binder.java:367)
        at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:2438)
        at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:3142)
        at android.os.Binder.execTransact(Binder.java:565)
     Caused by: android.system.ErrnoException: write failed: EPIPE (Broken pipe)
        at libcore.io.Posix.writeBytes(Native Method)
        at libcore.io.Posix.write(Posix.java:273)
        at libcore.io.BlockGuardOs.write(BlockGuardOs.java:319)
        at libcore.io.IoBridge.write(IoBridge.java:496)
        at java.io.FileOutputStream.write(FileOutputStream.java:316) 
        at com.android.internal.util.FastPrintWriter.flushBytesLocked(FastPrintWriter.java:336) 
        at com.android.internal.util.FastPrintWriter.flushLocked(FastPrintWriter.java:359) 
        at com.android.internal.util.FastPrintWriter.flush(FastPrintWriter.java:394) 
        at android.os.ShellCommand.exec(ShellCommand.java:113) 
        at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:18629) 
        at android.os.Binder.shellCommand(Binder.java:468) 
        at android.os.Binder.onTransact(Binder.java:367) 
        at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:2438) 
        at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:3142) 
        at android.os.Binder.execTransact(Binder.java:565) 
2019-07-28 20:47:40.904 5926-5926/? I/studio.deploy: package
2019-07-28 20:47:40.904 5926-5926/? I/studio.deploy: install-commit
2019-07-28 20:47:40.904 5926-5926/? I/studio.deploy: 1309473271
2019-07-28 20:47:40.966 1022-2091/system_process W/zipro: Error opening archive /data/app/vmdl1309473271.tmp/base.apk: Invalid file
2019-07-28 20:47:40.967 1022-2091/system_process D/asset: failed to open Zip archive '/data/app/vmdl1309473271.tmp/base.apk'
2019-07-28 20:47:40.972 1022-2091/system_process E/PackageInstaller: Commit of session 1309473271 failed: Failed to parse /data/app/vmdl1309473271.tmp/base.apk: AndroidManifest.xml