now it deleted the contents of the compressed encrypted file (as i
wanted) but it crashed

-rw------- 1 u0_a102 u0_a102       12 2019-08-03 12:47 data.aes.iv
-rw------- 1 u0_a102 u0_a102       10 2019-08-03 12:47 data.aes.gz

2019-08-03 12:47:48.070 6947-6947/com.example.quizactivity D/martin: required permissions obtained
2019-08-03 12:47:48.344 6947-6947/com.example.quizactivity D/AndroidRuntime: Shutting down VM
2019-08-03 12:47:48.346 6947-6947/com.example.quizactivity E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.quizactivity, PID: 6947
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.quizactivity/com.example.quizactivity.MainActivity}: java.io.EOFException
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2684)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2751)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1496)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6186)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
     Caused by: java.io.EOFException
        at java.util.zip.GZIPInputStream.readUByte(GZIPInputStream.java:263)
        at java.util.zip.GZIPInputStream.readUShort(GZIPInputStream.java:253)
        at java.util.zip.GZIPInputStream.readHeader(GZIPInputStream.java:162)
        at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:77)
        at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:89)
        at com.example.quizactivity.MainActivity.decrypt_gzip_stream(MainActivity.kt:63)
        at com.example.quizactivity.MainActivity.onCreate(MainActivity.kt:97)
        at android.app.Activity.performCreate(Activity.java:6684)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2637)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2751) 
        at android.app.ActivityThread.-wrap12(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1496) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6186) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779) 
2019-08-03 12:47:54.278 6947-6956/com.example.quizactivity E/System: Uncaught exception thrown by finalizer
2019-08-03 12:47:54.288 6947-6956/com.example.quizactivity E/System: java.lang.IllegalStateException: Binder has been finalized!
        at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(Binder.java:615)
        at android.security.IKeystoreService$Stub$Proxy.abort(IKeystoreService.java:1349)
        at android.security.KeyStore.abort(KeyStore.java:519)
        at android.security.keystore.AndroidKeyStoreCipherSpiBase.finalize(AndroidKeyStoreCipherSpiBase.java:744)
        at android.security.keystore.AndroidKeyStoreAuthenticatedAESCipherSpi$GCM$NoPadding.finalize(AndroidKeyStoreAuthenticatedAESCipherSpi.java)
        at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:222)
        at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:209)
        at java.lang.Thread.run(Thread.java:761)
2019-08-03 12:47:54.290 6947-6956/com.example.quizactivity E/System: Uncaught exception thrown by finalizer
2019-08-03 12:47:54.291 6947-6956/com.example.quizactivity E/System: java.lang.IllegalStateException: Binder has been finalized!
        at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(Binder.java:615)
        at android.security.IKeystoreService$Stub$Proxy.abort(IKeystoreService.java:1349)
        at android.security.KeyStore.abort(KeyStore.java:519)
        at android.security.keystore.AndroidKeyStoreCipherSpiBase.finalize(AndroidKeyStoreCipherSpiBase.java:744)
        at android.security.keystore.AndroidKeyStoreAuthenticatedAESCipherSpi$GCM$NoPadding.finalize(AndroidKeyStoreAuthenticatedAESCipherSpi.java)
        at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:222)
        at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:209)
        at java.lang.Thread.run(Thread.java:761)