it enumerates 2 cameras but complains about lifecycler
    java.lang.NoSuchMethodError: No super method
    getLifecycle()Landroidx/lifecycle/Lifecycle; in class
    Landroidx/core/app/ComponentActivity; or its super
    classes (declaration of 'androidx.core.app.ComponentActivity'
    appears in /data/app/com.example.quizactivity-2/base.apk)

2019-08-01 01:37:37.428 16203-16203/? I/art: Late-enabling -Xcheck:jni
2019-08-01 01:37:37.494 16203-16203/com.example.quizactivity W/System: ClassLoader referenced unknown path: /data/app/com.example.quizactivity-2/lib/arm64
2019-08-01 01:37:37.516 16203-16203/com.example.quizactivity D/Camera2Initializer: CameraX initializing with Camera2 ...
2019-08-01 01:37:37.519 16203-16203/com.example.quizactivity I/CameraManagerGlobal: Connecting to camera service
2019-08-01 01:37:37.564 16203-16203/com.example.quizactivity D/CameraRepository: Added camera: 0
2019-08-01 01:37:37.578 16203-16203/com.example.quizactivity D/CameraRepository: Added camera: 1
2019-08-01 01:37:37.581 16203-16219/com.example.quizactivity D/UseCaseAttachState: Active and online use case: [] for camera: 0
2019-08-01 01:37:37.582 16203-16219/com.example.quizactivity D/UseCaseAttachState: Active and online use case: [] for camera: 1
2019-08-01 01:37:37.615 16203-16203/com.example.quizactivity W/art: Before Android 4.1, method android.graphics.PorterDuffColorFilter androidx.vectordrawable.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
2019-08-01 01:37:37.617 16203-16203/com.example.quizactivity D/martin: onCreate
2019-08-01 01:37:37.648 16203-16203/com.example.quizactivity I/art: Rejecting re-init on previously-failed class java.lang.Class<androidx.core.view.ViewCompat$2>: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/view/View$OnUnhandledKeyEventListener;
2019-08-01 01:37:37.648 16203-16203/com.example.quizactivity I/art:     at void androidx.core.view.ViewCompat.setBackground(android.view.View, android.graphics.drawable.Drawable) (ViewCompat.java:2559)
2019-08-01 01:37:37.648 16203-16203/com.example.quizactivity I/art:     at void androidx.appcompat.widget.ActionBarContainer.<init>(android.content.Context, android.util.AttributeSet) (ActionBarContainer.java:62)
2019-08-01 01:37:37.648 16203-16203/com.example.quizactivity I/art:     at java.lang.Object java.lang.reflect.Constructor.newInstance0!(java.lang.Object[]) (Constructor.java:-2)
2019-08-01 01:37:37.648 16203-16203/com.example.quizactivity I/art:     at java.lang.Object java.lang.reflect.Constructor.newInstance(java.lang.Object[]) (Constructor.java:430)
2019-08-01 01:37:37.648 16203-16203/com.example.quizactivity I/art:     at android.view.View android.view.LayoutInflater.createView(java.lang.String, java.lang.String, android.util.AttributeSet) (LayoutInflater.java:645)
2019-08-01 01:37:37.648 16203-16203/com.example.quizactivity I/art:     at android.view.View android.view.LayoutInflater.createViewFromTag(android.view.View, java.lang.String, android.content.Context, android.util.AttributeSet, boolean) (LayoutInflater.java:787)
2019-08-01 01:37:37.648 16203-16203/com.example.quizactivity I/art:     at android.view.View android.view.LayoutInflater.createViewFromTag(android.view.View, java.lang.String, android.content.Context, android.util.AttributeSet) (LayoutInflater.java:727)
2019-08-01 01:37:37.648 16203-16203/com.example.quizactivity I/art:     at void android.view.LayoutInflater.rInflate(org.xmlpull.v1.XmlPullParser, android.view.View, android.content.Context, android.util.AttributeSet, boolean) (LayoutInflater.java:858)
2019-08-01 01:37:37.649 16203-16203/com.example.quizactivity I/art:     at void android.view.LayoutInflater.rInflateChildren(org.xmlpull.v1.XmlPullParser, android.view.View, android.util.AttributeSet, boolean) (LayoutInflater.java:821)
2019-08-01 01:37:37.649 16203-16203/com.example.quizactivity I/art:     at android.view.View android.view.LayoutInflater.inflate(org.xmlpull.v1.XmlPullParser, android.view.ViewGroup, boolean) (LayoutInflater.java:518)
2019-08-01 01:37:37.649 16203-16203/com.example.quizactivity I/art:     at android.view.View android.view.LayoutInflater.inflate(int, android.view.ViewGroup, boolean) (LayoutInflater.java:426)
2019-08-01 01:37:37.649 16203-16203/com.example.quizactivity I/art:     at android.view.View android.view.LayoutInflater.inflate(int, android.view.ViewGroup) (LayoutInflater.java:377)
2019-08-01 01:37:37.649 16203-16203/com.example.quizactivity I/art:     at android.view.ViewGroup androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor() (AppCompatDelegateImpl.java:607)
2019-08-01 01:37:37.649 16203-16203/com.example.quizactivity I/art:     at void androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor() (AppCompatDelegateImpl.java:518)
2019-08-01 01:37:37.649 16203-16203/com.example.quizactivity I/art:     at void androidx.appcompat.app.AppCompatDelegateImpl.setContentView(int) (AppCompatDelegateImpl.java:466)
2019-08-01 01:37:37.649 16203-16203/com.example.quizactivity I/art:     at void androidx.appcompat.app.AppCompatActivity.setContentView(int) (AppCompatActivity.java:140)
2019-08-01 01:37:37.649 16203-16203/com.example.quizactivity I/art:     at void com.example.quizactivity.MainActivity.onCreate(android.os.Bundle) (MainActivity.kt:29)
2019-08-01 01:37:37.649 16203-16203/com.example.quizactivity I/art:     at void android.app.Activity.performCreate(android.os.Bundle) (Activity.java:6684)
2019-08-01 01:37:37.649 16203-16203/com.example.quizactivity I/art:     at void android.app.Instrumentation.callActivityOnCreate(android.app.Activity, android.os.Bundle) (Instrumentation.java:1119)
2019-08-01 01:37:37.649 16203-16203/com.example.quizactivity I/art:     at android.app.Activity android.app.ActivityThread.performLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent) (ActivityThread.java:2637)
2019-08-01 01:37:37.649 16203-16203/com.example.quizactivity I/art:     at void android.app.ActivityThread.handleLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:2751)
2019-08-01 01:37:37.649 16203-16203/com.example.quizactivity I/art:     at void android.app.ActivityThread.-wrap12(android.app.ActivityThread, android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:-1)
2019-08-01 01:37:37.649 16203-16203/com.example.quizactivity I/art:     at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1496)
2019-08-01 01:37:37.649 16203-16203/com.example.quizactivity I/art:     at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:102)
2019-08-01 01:37:37.650 16203-16203/com.example.quizactivity I/art:     at void android.os.Looper.loop() (Looper.java:154)
2019-08-01 01:37:37.650 16203-16203/com.example.quizactivity I/art:     at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6186)
2019-08-01 01:37:37.650 16203-16203/com.example.quizactivity I/art:     at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
2019-08-01 01:37:37.650 16203-16203/com.example.quizactivity I/art:     at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:889)
2019-08-01 01:37:37.650 16203-16203/com.example.quizactivity I/art:     at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:779)
2019-08-01 01:37:37.650 16203-16203/com.example.quizactivity I/art: Caused by: java.lang.ClassNotFoundException: Didn't find class "android.view.View$OnUnhandledKeyEventListener" on path: DexPathList[[zip file "/data/app/com.example.quizactivity-2/base.apk"],nativeLibraryDirectories=[/data/app/com.example.quizactivity-2/lib/arm64, /system/lib64, /vendor/lib64]]
2019-08-01 01:37:37.650 16203-16203/com.example.quizactivity I/art:     at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:56)
2019-08-01 01:37:37.650 16203-16203/com.example.quizactivity I/art:     at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:380)
2019-08-01 01:37:37.650 16203-16203/com.example.quizactivity I/art:     at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
2019-08-01 01:37:37.650 16203-16203/com.example.quizactivity I/art:     at void androidx.core.view.ViewCompat.setBackground(android.view.View, android.graphics.drawable.Drawable) (ViewCompat.java:2559)
2019-08-01 01:37:37.650 16203-16203/com.example.quizactivity I/art:     at void androidx.appcompat.widget.ActionBarContainer.<init>(android.content.Context, android.util.AttributeSet) (ActionBarContainer.java:62)
2019-08-01 01:37:37.650 16203-16203/com.example.quizactivity I/art:     at java.lang.Object java.lang.reflect.Constructor.newInstance0!(java.lang.Object[]) (Constructor.java:-2)
2019-08-01 01:37:37.650 16203-16203/com.example.quizactivity I/art:     at java.lang.Object java.lang.reflect.Constructor.newInstance(java.lang.Object[]) (Constructor.java:430)
2019-08-01 01:37:37.650 16203-16203/com.example.quizactivity I/art:     at android.view.View android.view.LayoutInflater.createView(java.lang.String, java.lang.String, android.util.AttributeSet) (LayoutInflater.java:645)
2019-08-01 01:37:37.650 16203-16203/com.example.quizactivity I/art:     at android.view.View android.view.LayoutInflater.createViewFromTag(android.view.View, java.lang.String, android.content.Context, android.util.AttributeSet, boolean) (LayoutInflater.java:787)
2019-08-01 01:37:37.650 16203-16203/com.example.quizactivity I/art:     at android.view.View android.view.LayoutInflater.createViewFromTag(android.view.View, java.lang.String, android.content.Context, android.util.AttributeSet) (LayoutInflater.java:727)
2019-08-01 01:37:37.650 16203-16203/com.example.quizactivity I/art:     at void android.view.LayoutInflater.rInflate(org.xmlpull.v1.XmlPullParser, android.view.View, android.content.Context, android.util.AttributeSet, boolean) (LayoutInflater.java:858)
2019-08-01 01:37:37.650 16203-16203/com.example.quizactivity I/art:     at void android.view.LayoutInflater.rInflateChildren(org.xmlpull.v1.XmlPullParser, android.view.View, android.util.AttributeSet, boolean) (LayoutInflater.java:821)
2019-08-01 01:37:37.650 16203-16203/com.example.quizactivity I/art:     at android.view.View android.view.LayoutInflater.inflate(org.xmlpull.v1.XmlPullParser, android.view.ViewGroup, boolean) (LayoutInflater.java:518)
2019-08-01 01:37:37.650 16203-16203/com.example.quizactivity I/art:     at android.view.View android.view.LayoutInflater.inflate(int, android.view.ViewGroup, boolean) (LayoutInflater.java:426)
2019-08-01 01:37:37.650 16203-16203/com.example.quizactivity I/art:     at android.view.View android.view.LayoutInflater.inflate(int, android.view.ViewGroup) (LayoutInflater.java:377)
2019-08-01 01:37:37.650 16203-16203/com.example.quizactivity I/art:     at android.view.ViewGroup androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor() (AppCompatDelegateImpl.java:607)
2019-08-01 01:37:37.650 16203-16203/com.example.quizactivity I/art:     at void androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor() (AppCompatDelegateImpl.java:518)
2019-08-01 01:37:37.650 16203-16203/com.example.quizactivity I/art:     at void androidx.appcompat.app.AppCompatDelegateImpl.setContentView(int) (AppCompatDelegateImpl.java:466)
2019-08-01 01:37:37.650 16203-16203/com.example.quizactivity I/art:     at void androidx.appcompat.app.AppCompatActivity.setContentView(int) (AppCompatActivity.java:140)
2019-08-01 01:37:37.650 16203-16203/com.example.quizactivity I/art:     at void com.example.quizactivity.MainActivity.onCreate(android.os.Bundle) (MainActivity.kt:29)
2019-08-01 01:37:37.650 16203-16203/com.example.quizactivity I/art:     at void android.app.Activity.performCreate(android.os.Bundle) (Activity.java:6684)
2019-08-01 01:37:37.650 16203-16203/com.example.quizactivity I/art:     at void android.app.Instrumentation.callActivityOnCreate(android.app.Activity, android.os.Bundle) (Instrumentation.java:1119)
2019-08-01 01:37:37.650 16203-16203/com.example.quizactivity I/art:     at android.app.Activity android.app.ActivityThread.performLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent) (ActivityThread.java:2637)
2019-08-01 01:37:37.650 16203-16203/com.example.quizactivity I/art:     at void android.app.ActivityThread.handleLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:2751)
2019-08-01 01:37:37.650 16203-16203/com.example.quizactivity I/art:     at void android.app.ActivityThread.-wrap12(android.app.ActivityThread, android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:-1)
2019-08-01 01:37:37.651 16203-16203/com.example.quizactivity I/art:     at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1496)
2019-08-01 01:37:37.651 16203-16203/com.example.quizactivity I/art:     at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:102)
2019-08-01 01:37:37.651 16203-16203/com.example.quizactivity I/art:     at void android.os.Looper.loop() (Looper.java:154)
2019-08-01 01:37:37.651 16203-16203/com.example.quizactivity I/art:     at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6186)
2019-08-01 01:37:37.651 16203-16203/com.example.quizactivity I/art:     at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
2019-08-01 01:37:37.651 16203-16203/com.example.quizactivity I/art:     at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:889)
2019-08-01 01:37:37.651 16203-16203/com.example.quizactivity I/art:     at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:779)
2019-08-01 01:37:37.771 16203-16203/com.example.quizactivity D/martin: onStart
2019-08-01 01:37:37.772 16203-16203/com.example.quizactivity D/martin: onPostCreate
2019-08-01 01:37:37.776 16203-16203/com.example.quizactivity D/martin: onResume
2019-08-01 01:37:37.779 16203-16203/com.example.quizactivity D/martin: onPostResume
2019-08-01 01:37:37.805 16203-16203/com.example.quizactivity D/martin: onPause
2019-08-01 01:37:37.856 16203-16220/com.example.quizactivity I/Adreno: QUALCOMM build                   : 6818200, Idb2b4cb785
    Build Date                       : 11/18/16
    OpenGL ES Shader Compiler Version: XE031.09.00.04
    Local Branch                     : N25
    Remote Branch                    :
    Remote Branch                    :
    Reconstruct Branch               :
2019-08-01 01:37:37.865 16203-16220/com.example.quizactivity I/OpenGLRenderer: Initialized EGL, version 1.4
2019-08-01 01:37:37.866 16203-16220/com.example.quizactivity D/OpenGLRenderer: Swap behavior 1
2019-08-01 01:37:40.201 16203-16203/com.example.quizactivity D/martin: onResume
2019-08-01 01:37:40.201 16203-16203/com.example.quizactivity D/martin: onPostResume
2019-08-01 01:37:40.265 16203-16203/com.example.quizactivity D/AndroidRuntime: Shutting down VM
2019-08-01 01:37:40.266 16203-16203/com.example.quizactivity E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.quizactivity, PID: 16203
    java.lang.NoSuchMethodError: No super method getLifecycle()Landroidx/lifecycle/Lifecycle; in class Landroidx/core/app/ComponentActivity; or its super classes (declaration of 'androidx.core.app.ComponentActivity' appears in /data/app/com.example.quizactivity-2/base.apk)
        at androidx.fragment.app.FragmentActivity.getLifecycle(FragmentActivity.java:324)
        at androidx.camera.core.UseCaseGroupRepository.createUseCaseGroup(UseCaseGroupRepository.java:109)
        at androidx.camera.core.UseCaseGroupRepository.getOrCreateUseCaseGroup(UseCaseGroupRepository.java:88)
        at androidx.camera.core.CameraX.getOrCreateUseCaseGroup(CameraX.java:572)
        at androidx.camera.core.CameraX.bindToLifecycle(CameraX.java:167)
        at com.example.quizactivity.MainActivity.startCamera(MainActivity.kt:98)
        at com.example.quizactivity.MainActivity.access$startCamera(MainActivity.kt:25)
        at com.example.quizactivity.MainActivity$onRequestPermissionsResult$1.invoke(MainActivity.kt:125)
        at com.example.quizactivity.MainActivity$onRequestPermissionsResult$1.run(MainActivity.kt:25)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6186)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)