apk runs but i don't have a server
2019-08-01 04:24:07.836 25736-25736/? I/art: Late-enabling -Xcheck:jni
2019-08-01 04:24:07.890 25736-25736/com.example.quizactivity W/System: ClassLoader referenced unknown path: /data/app/com.example.quizactivity-2/lib/arm64
2019-08-01 04:24:07.935 25736-25736/com.example.quizactivity W/art: Before Android 4.1, method android.graphics.PorterDuffColorFilter androidx.vectordrawable.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
2019-08-01 04:24:07.941 25736-25736/com.example.quizactivity D/martin: onCreate
2019-08-01 04:24:07.971 25736-25736/com.example.quizactivity I/art: Rejecting re-init on previously-failed class java.lang.Class<androidx.core.view.ViewCompat$2>: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/view/View$OnUnhandledKeyEventListener;
2019-08-01 04:24:07.971 25736-25736/com.example.quizactivity I/art:     at void androidx.core.view.ViewCompat.setBackground(android.view.View, android.graphics.drawable.Drawable) (ViewCompat.java:2561)
2019-08-01 04:24:07.971 25736-25736/com.example.quizactivity I/art:     at void androidx.appcompat.widget.ActionBarContainer.<init>(android.content.Context, android.util.AttributeSet) (ActionBarContainer.java:63)
2019-08-01 04:24:07.971 25736-25736/com.example.quizactivity I/art:     at java.lang.Object java.lang.reflect.Constructor.newInstance0!(java.lang.Object[]) (Constructor.java:-2)
2019-08-01 04:24:07.971 25736-25736/com.example.quizactivity I/art:     at java.lang.Object java.lang.reflect.Constructor.newInstance(java.lang.Object[]) (Constructor.java:430)
2019-08-01 04:24:07.971 25736-25736/com.example.quizactivity I/art:     at android.view.View android.view.LayoutInflater.createView(java.lang.String, java.lang.String, android.util.AttributeSet) (LayoutInflater.java:645)
2019-08-01 04:24:07.971 25736-25736/com.example.quizactivity I/art:     at android.view.View android.view.LayoutInflater.createViewFromTag(android.view.View, java.lang.String, android.content.Context, android.util.AttributeSet, boolean) (LayoutInflater.java:787)
2019-08-01 04:24:07.971 25736-25736/com.example.quizactivity I/art:     at android.view.View android.view.LayoutInflater.createViewFromTag(android.view.View, java.lang.String, android.content.Context, android.util.AttributeSet) (LayoutInflater.java:727)
2019-08-01 04:24:07.971 25736-25736/com.example.quizactivity I/art:     at void android.view.LayoutInflater.rInflate(org.xmlpull.v1.XmlPullParser, android.view.View, android.content.Context, android.util.AttributeSet, boolean) (LayoutInflater.java:858)
2019-08-01 04:24:07.971 25736-25736/com.example.quizactivity I/art:     at void android.view.LayoutInflater.rInflateChildren(org.xmlpull.v1.XmlPullParser, android.view.View, android.util.AttributeSet, boolean) (LayoutInflater.java:821)
2019-08-01 04:24:07.971 25736-25736/com.example.quizactivity I/art:     at android.view.View android.view.LayoutInflater.inflate(org.xmlpull.v1.XmlPullParser, android.view.ViewGroup, boolean) (LayoutInflater.java:518)
2019-08-01 04:24:07.972 25736-25736/com.example.quizactivity I/art:     at android.view.View android.view.LayoutInflater.inflate(int, android.view.ViewGroup, boolean) (LayoutInflater.java:426)
2019-08-01 04:24:07.972 25736-25736/com.example.quizactivity I/art:     at android.view.View android.view.LayoutInflater.inflate(int, android.view.ViewGroup) (LayoutInflater.java:377)
2019-08-01 04:24:07.972 25736-25736/com.example.quizactivity I/art:     at android.view.ViewGroup androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor() (AppCompatDelegateImpl.java:720)
2019-08-01 04:24:07.972 25736-25736/com.example.quizactivity I/art:     at void androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor() (AppCompatDelegateImpl.java:630)
2019-08-01 04:24:07.972 25736-25736/com.example.quizactivity I/art:     at void androidx.appcompat.app.AppCompatDelegateImpl.setContentView(int) (AppCompatDelegateImpl.java:529)
2019-08-01 04:24:07.972 25736-25736/com.example.quizactivity I/art:     at void androidx.appcompat.app.AppCompatActivity.setContentView(int) (AppCompatActivity.java:161)
2019-08-01 04:24:07.972 25736-25736/com.example.quizactivity I/art:     at void com.example.quizactivity.MainActivity.onCreate(android.os.Bundle) (MainActivity.kt:19)
2019-08-01 04:24:07.972 25736-25736/com.example.quizactivity I/art:     at void android.app.Activity.performCreate(android.os.Bundle) (Activity.java:6684)
2019-08-01 04:24:07.972 25736-25736/com.example.quizactivity I/art:     at void android.app.Instrumentation.callActivityOnCreate(android.app.Activity, android.os.Bundle) (Instrumentation.java:1119)
2019-08-01 04:24:07.972 25736-25736/com.example.quizactivity I/art:     at android.app.Activity android.app.ActivityThread.performLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent) (ActivityThread.java:2637)
2019-08-01 04:24:07.972 25736-25736/com.example.quizactivity I/art:     at void android.app.ActivityThread.handleLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:2751)
2019-08-01 04:24:07.972 25736-25736/com.example.quizactivity I/art:     at void android.app.ActivityThread.-wrap12(android.app.ActivityThread, android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:-1)
2019-08-01 04:24:07.972 25736-25736/com.example.quizactivity I/art:     at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1496)
2019-08-01 04:24:07.972 25736-25736/com.example.quizactivity I/art:     at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:102)
2019-08-01 04:24:07.972 25736-25736/com.example.quizactivity I/art:     at void android.os.Looper.loop() (Looper.java:154)
2019-08-01 04:24:07.972 25736-25736/com.example.quizactivity I/art:     at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6186)
2019-08-01 04:24:07.972 25736-25736/com.example.quizactivity I/art:     at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
2019-08-01 04:24:07.972 25736-25736/com.example.quizactivity I/art:     at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:889)
2019-08-01 04:24:07.972 25736-25736/com.example.quizactivity I/art:     at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:779)
2019-08-01 04:24:07.972 25736-25736/com.example.quizactivity I/art: Caused by: java.lang.ClassNotFoundException: Didn't find class "android.view.View$OnUnhandledKeyEventListener" on path: DexPathList[[zip file "/data/app/com.example.quizactivity-2/base.apk"],nativeLibraryDirectories=[/data/app/com.example.quizactivity-2/lib/arm64, /system/lib64, /vendor/lib64]]
2019-08-01 04:24:07.972 25736-25736/com.example.quizactivity I/art:     at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:56)
2019-08-01 04:24:07.972 25736-25736/com.example.quizactivity I/art:     at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:380)
2019-08-01 04:24:07.972 25736-25736/com.example.quizactivity I/art:     at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
2019-08-01 04:24:07.972 25736-25736/com.example.quizactivity I/art:     at void androidx.core.view.ViewCompat.setBackground(android.view.View, android.graphics.drawable.Drawable) (ViewCompat.java:2561)
2019-08-01 04:24:07.972 25736-25736/com.example.quizactivity I/art:     at void androidx.appcompat.widget.ActionBarContainer.<init>(android.content.Context, android.util.AttributeSet) (ActionBarContainer.java:63)
2019-08-01 04:24:07.972 25736-25736/com.example.quizactivity I/art:     at java.lang.Object java.lang.reflect.Constructor.newInstance0!(java.lang.Object[]) (Constructor.java:-2)
2019-08-01 04:24:07.972 25736-25736/com.example.quizactivity I/art:     at java.lang.Object java.lang.reflect.Constructor.newInstance(java.lang.Object[]) (Constructor.java:430)
2019-08-01 04:24:07.972 25736-25736/com.example.quizactivity I/art:     at android.view.View android.view.LayoutInflater.createView(java.lang.String, java.lang.String, android.util.AttributeSet) (LayoutInflater.java:645)
2019-08-01 04:24:07.972 25736-25736/com.example.quizactivity I/art:     at android.view.View android.view.LayoutInflater.createViewFromTag(android.view.View, java.lang.String, android.content.Context, android.util.AttributeSet, boolean) (LayoutInflater.java:787)
2019-08-01 04:24:07.972 25736-25736/com.example.quizactivity I/art:     at android.view.View android.view.LayoutInflater.createViewFromTag(android.view.View, java.lang.String, android.content.Context, android.util.AttributeSet) (LayoutInflater.java:727)
2019-08-01 04:24:07.972 25736-25736/com.example.quizactivity I/art:     at void android.view.LayoutInflater.rInflate(org.xmlpull.v1.XmlPullParser, android.view.View, android.content.Context, android.util.AttributeSet, boolean) (LayoutInflater.java:858)
2019-08-01 04:24:07.972 25736-25736/com.example.quizactivity I/art:     at void android.view.LayoutInflater.rInflateChildren(org.xmlpull.v1.XmlPullParser, android.view.View, android.util.AttributeSet, boolean) (LayoutInflater.java:821)
2019-08-01 04:24:07.973 25736-25736/com.example.quizactivity I/art:     at android.view.View android.view.LayoutInflater.inflate(org.xmlpull.v1.XmlPullParser, android.view.ViewGroup, boolean) (LayoutInflater.java:518)
2019-08-01 04:24:07.973 25736-25736/com.example.quizactivity I/art:     at android.view.View android.view.LayoutInflater.inflate(int, android.view.ViewGroup, boolean) (LayoutInflater.java:426)
2019-08-01 04:24:07.973 25736-25736/com.example.quizactivity I/art:     at android.view.View android.view.LayoutInflater.inflate(int, android.view.ViewGroup) (LayoutInflater.java:377)
2019-08-01 04:24:07.973 25736-25736/com.example.quizactivity I/art:     at android.view.ViewGroup androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor() (AppCompatDelegateImpl.java:720)
2019-08-01 04:24:07.973 25736-25736/com.example.quizactivity I/art:     at void androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor() (AppCompatDelegateImpl.java:630)
2019-08-01 04:24:07.973 25736-25736/com.example.quizactivity I/art:     at void androidx.appcompat.app.AppCompatDelegateImpl.setContentView(int) (AppCompatDelegateImpl.java:529)
2019-08-01 04:24:07.973 25736-25736/com.example.quizactivity I/art:     at void androidx.appcompat.app.AppCompatActivity.setContentView(int) (AppCompatActivity.java:161)
2019-08-01 04:24:07.973 25736-25736/com.example.quizactivity I/art:     at void com.example.quizactivity.MainActivity.onCreate(android.os.Bundle) (MainActivity.kt:19)
2019-08-01 04:24:07.973 25736-25736/com.example.quizactivity I/art:     at void android.app.Activity.performCreate(android.os.Bundle) (Activity.java:6684)
2019-08-01 04:24:07.973 25736-25736/com.example.quizactivity I/art:     at void android.app.Instrumentation.callActivityOnCreate(android.app.Activity, android.os.Bundle) (Instrumentation.java:1119)
2019-08-01 04:24:07.973 25736-25736/com.example.quizactivity I/art:     at android.app.Activity android.app.ActivityThread.performLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent) (ActivityThread.java:2637)
2019-08-01 04:24:07.973 25736-25736/com.example.quizactivity I/art:     at void android.app.ActivityThread.handleLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:2751)
2019-08-01 04:24:07.973 25736-25736/com.example.quizactivity I/art:     at void android.app.ActivityThread.-wrap12(android.app.ActivityThread, android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:-1)
2019-08-01 04:24:07.973 25736-25736/com.example.quizactivity I/art:     at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1496)
2019-08-01 04:24:07.973 25736-25736/com.example.quizactivity I/art:     at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:102)
2019-08-01 04:24:07.973 25736-25736/com.example.quizactivity I/art:     at void android.os.Looper.loop() (Looper.java:154)
2019-08-01 04:24:07.973 25736-25736/com.example.quizactivity I/art:     at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6186)
2019-08-01 04:24:07.973 25736-25736/com.example.quizactivity I/art:     at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
2019-08-01 04:24:07.973 25736-25736/com.example.quizactivity I/art:     at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:889)
2019-08-01 04:24:07.973 25736-25736/com.example.quizactivity I/art:     at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:779)
2019-08-01 04:24:08.137 25736-25736/com.example.quizactivity W/art: Before Android 4.1, method double java.util.concurrent.ThreadLocalRandom.internalNextDouble(double, double) would have incorrectly overridden the package-private method in java.util.Random
2019-08-01 04:24:08.137 25736-25736/com.example.quizactivity W/art: Before Android 4.1, method int java.util.concurrent.ThreadLocalRandom.internalNextInt(int, int) would have incorrectly overridden the package-private method in java.util.Random
2019-08-01 04:24:08.137 25736-25736/com.example.quizactivity W/art: Before Android 4.1, method long java.util.concurrent.ThreadLocalRandom.internalNextLong(long, long) would have incorrectly overridden the package-private method in java.util.Random
2019-08-01 04:24:08.162 25736-25736/com.example.quizactivity D/martin: onStart
2019-08-01 04:24:08.163 25736-25736/com.example.quizactivity D/martin: onPostCreate
2019-08-01 04:24:08.168 25736-25736/com.example.quizactivity D/martin: onResume
2019-08-01 04:24:08.170 25736-25736/com.example.quizactivity D/martin: onPostResume
2019-08-01 04:24:08.232 25736-25757/com.example.quizactivity I/Adreno: QUALCOMM build                   : 6818200, Idb2b4cb785
    Build Date                       : 11/18/16
    OpenGL ES Shader Compiler Version: XE031.09.00.04
    Local Branch                     : N25
    Remote Branch                    :
    Remote Branch                    :
    Reconstruct Branch               :
2019-08-01 04:24:08.241 25736-25757/com.example.quizactivity I/OpenGLRenderer: Initialized EGL, version 1.4
2019-08-01 04:24:08.241 25736-25757/com.example.quizactivity D/OpenGLRenderer: Swap behavior 1